//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::music::Entity as Music;
pub use super::notes::Entity as Notes;
pub use super::songs::Entity as Songs;
pub use super::tests::Entity as Tests;
pub use super::users::Entity as Users;
